# Generated by Django 4.2.4 on 2023-08-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('phone', models.BigIntegerField(verbose_name='phone')),
                ('email', models.EmailField(max_length=30, verbose_name='email')),
            ],
        ),
    ]
